"""Concrete insurance workflow examples for the TACO demo."""

from __future__ import annotations


INSURANCE_SCENARIOS = [
    {
        "scenario_id": "IW-001",
        "insured": "Apex Robotics",
        "robot": "warehouse manipulation arm",
        "coverage": "Learned-Policy Liability",
        "failure": "Occlusion-induced wrong grasp damages customer inventory.",
        "evidence_identified": "Target feature collapses 1.04s before the wrong grasp while occlusion risk rises.",
        "pricing": {"with_controls_monthly_usd": 29800, "without_controls_monthly_usd": 51500},
        "required_control": "occlusion_risk_monitor_enabled",
        "exclusion_if_missing": "Known occlusion-induced target collapse excluded until monitor is enabled.",
        "workflow": [
            "Buyer submits pre-deployment application with no loss history.",
            "TACO loads FR-001 replay certificate and success/failure/mitigated GIFs.",
            "Trace analyzer identifies early target-feature collapse.",
            "Quote engine applies monitor discount when second-view control is enabled.",
            "Binder attaches FR-001 exclusion if the monitor is disabled.",
        ],
    },
    {
        "scenario_id": "IW-002",
        "insured": "Northstar Fulfillment",
        "robot": "mobile picking cobot",
        "coverage": "Warehouse Property And Operations Liability",
        "failure": "Language override routes a pick action to the wrong tote, creating a contractual chargeback.",
        "evidence_identified": "Language override risk dominates action selection while visual target confidence stays stable.",
        "pricing": {"with_controls_monthly_usd": 18400, "without_controls_monthly_usd": 32700},
        "required_control": "language_override_sanitizer_enabled",
        "exclusion_if_missing": "Instruction-conflict failures excluded until sanitizer is enabled.",
        "workflow": [
            "Broker imports the customer workflow and requested coverage limit.",
            "DreamAudit-style replay mutates the benign instruction with a conflicting suffix.",
            "Internal trace shows language risk, not vision risk, caused the action.",
            "Underwriter requires sanitizer logs as a coverage condition.",
            "Renewal file compares chargeback incidents against sanitizer compliance.",
        ],
    },
    {
        "scenario_id": "IW-003",
        "insured": "Harbor Retail Automation",
        "robot": "shelf restocking arm",
        "coverage": "Customer Premises Liability",
        "failure": "Semantic distractor confusion causes the arm to place a heavy item on an unstable shelf.",
        "evidence_identified": "Target identity margin collapses near visually similar inventory.",
        "pricing": {"with_controls_monthly_usd": 22100, "without_controls_monthly_usd": 36600},
        "required_control": "target_identity_confirmation_enabled",
        "exclusion_if_missing": "Semantic distractor confusion excluded in high-similarity inventory layouts.",
        "workflow": [
            "Enterprise risk team uploads planned SKU layout.",
            "TACO maps layout similarity to known distractor failure families.",
            "Replay evidence shows success, failure, and target-confirmed mitigation.",
            "Quote requires target identity confirmation before shelf-contact actions.",
            "Binder lists high-similarity SKU layout changes as re-audit triggers.",
        ],
    },
    {
        "scenario_id": "IW-004",
        "insured": "Civic Food Robotics",
        "robot": "commercial kitchen prep arm",
        "coverage": "Product Contamination Liability",
        "failure": "Transparent object depth error causes a utensil to contact an unsafe surface.",
        "evidence_identified": "Depth uncertainty exceeds grasp-stability margin before the contact action.",
        "pricing": {"with_controls_monthly_usd": 26300, "without_controls_monthly_usd": 44800},
        "required_control": "depth_uncertainty_sensor_fusion",
        "exclusion_if_missing": "Transparent-object handling excluded without depth uncertainty gating.",
        "workflow": [
            "Kitchen operator requests coverage before deploying a prep arm.",
            "TACO stress-tests transparent and reflective objects.",
            "Evidence suite flags depth uncertainty as the dominant risk signal.",
            "Quote requires sensor fusion or excludes transparent-object tasks.",
            "Binder maps sanitation incidents to the recorded failure family.",
        ],
    },
    {
        "scenario_id": "IW-005",
        "insured": "Linehaul Parcel Systems",
        "robot": "sorting conveyor manipulator",
        "coverage": "Cargo Damage Liability",
        "failure": "Workspace boundary overreach knocks a parcel off the conveyor.",
        "evidence_identified": "Action risk rises near joint-limit boundary while task-completion confidence remains high.",
        "pricing": {"with_controls_monthly_usd": 31200, "without_controls_monthly_usd": 53900},
        "required_control": "workspace_geofence",
        "exclusion_if_missing": "Boundary overreach claims excluded after unreviewed layout changes.",
        "workflow": [
            "Ops team declares conveyor geometry and deployment units.",
            "TACO replay suite probes boundary and joint-limit conditions.",
            "Trace analyzer identifies overreach risk before parcel contact.",
            "Underwriter requires geofence configuration and layout re-audit.",
            "Premium updates when the customer changes conveyor geometry.",
        ],
    },
    {
        "scenario_id": "IW-006",
        "insured": "MedSupply Autonomy",
        "robot": "hospital supply delivery robot",
        "coverage": "Healthcare Operations Liability",
        "failure": "Camera glare pose drift causes delivery to the wrong medication cabinet.",
        "evidence_identified": "Pose estimate drifts while completion confidence remains high under glare.",
        "pricing": {"with_controls_monthly_usd": 34400, "without_controls_monthly_usd": 58700},
        "required_control": "pose_uncertainty_gate",
        "exclusion_if_missing": "Glare-induced pose drift excluded in unvalidated lighting conditions.",
        "workflow": [
            "Hospital buyer submits floor lighting and task route data.",
            "TACO replays glare perturbations against delivery tasks.",
            "Internal signal identifies pose drift before cabinet interaction.",
            "Quote requires pose uncertainty gating and lighting validation.",
            "Binder requires re-audit after route or lighting changes.",
        ],
    },
    {
        "scenario_id": "IW-007",
        "insured": "AgriLoop Robotics",
        "robot": "greenhouse harvesting arm",
        "coverage": "Crop Damage Liability",
        "failure": "Contact force overshoot bruises high-value produce.",
        "evidence_identified": "Force-risk feature spikes before completion signal crosses threshold.",
        "pricing": {"with_controls_monthly_usd": 19800, "without_controls_monthly_usd": 34100},
        "required_control": "force_governor",
        "exclusion_if_missing": "High-force harvest claims excluded without force governor telemetry.",
        "workflow": [
            "Grower requests per-season crop damage coverage.",
            "TACO searches small force and pose perturbations around harvest tasks.",
            "Replay evidence identifies minimal force overshoot failures.",
            "Quote applies lower premium when force governor logs are enabled.",
            "Claims file links bruising reports back to replayed failure boundaries.",
        ],
    },
    {
        "scenario_id": "IW-008",
        "insured": "Portside Maintenance AI",
        "robot": "inspection and repair robot",
        "coverage": "Third-Party Property Liability",
        "failure": "Drawer collision edge case scratches a customer asset during inspection.",
        "evidence_identified": "Transport feature rises but swept-volume clearance drops near articulated geometry.",
        "pricing": {"with_controls_monthly_usd": 27600, "without_controls_monthly_usd": 46300},
        "required_control": "swept_volume_clearance_monitor",
        "exclusion_if_missing": "Articulated-object collision damage excluded without clearance monitor.",
        "workflow": [
            "Service provider submits inspection task library.",
            "TACO identifies articulated-object edge cases in replay evidence.",
            "Trace metrics show clearance risk before physical collision.",
            "Underwriter requires swept-volume monitor for covered tasks.",
            "Binder lists new asset geometries as re-audit triggers.",
        ],
    },
    {
        "scenario_id": "IW-009",
        "insured": "SoftGoods Automation",
        "robot": "deformable goods packing robot",
        "coverage": "Operational Errors And Omissions",
        "failure": "Rope or strap entanglement causes a failed pack-out and missed shipment SLA.",
        "evidence_identified": "Memorized trajectory dominates deformable-object state during recovery.",
        "pricing": {"with_controls_monthly_usd": 24300, "without_controls_monthly_usd": 40200},
        "required_control": "deformable_recovery_monitor",
        "exclusion_if_missing": "Deformable-object entanglement excluded without recovery monitor.",
        "workflow": [
            "Customer submits SLA exposure and pack-out task mix.",
            "TACO runs rope and strap perturbation replays.",
            "Internal traces show memorized path bias during failed recovery.",
            "Quote requires recovery monitor and human escalation threshold.",
            "Renewal uses monitor compliance and SLA miss data to update pricing.",
        ],
    },
    {
        "scenario_id": "IW-010",
        "insured": "MetroLab Robotics",
        "robot": "multi-purpose lab automation arm",
        "coverage": "Research Equipment Liability",
        "failure": "Model update changes action behavior and invalidates prior safety evidence.",
        "evidence_identified": "Post-update replay no longer matches the certified failure boundary.",
        "pricing": {"with_controls_monthly_usd": 15700, "without_controls_monthly_usd": 28600},
        "required_control": "reaudit_required_after_model_update",
        "exclusion_if_missing": "Post-update learned-policy behavior excluded until re-audit is completed.",
        "workflow": [
            "Lab requests coverage for frequently updated robot policies.",
            "TACO records baseline replay certificates and quote conditions.",
            "Model update triggers required re-audit before coverage carries forward.",
            "Quote remains lower when update-gated re-audit workflow is enforced.",
            "Binder excludes post-update behavior if re-audit evidence is missing.",
        ],
    },
]


def scenario_summary() -> dict[str, int]:
    return {
        "scenarios": len(INSURANCE_SCENARIOS),
        "coverages": len({scenario["coverage"] for scenario in INSURANCE_SCENARIOS}),
        "controls": len({scenario["required_control"] for scenario in INSURANCE_SCENARIOS}),
    }
